## Pipeline stages ##
stages:
- compile
- build
- test
- chaos
- cleanup

## Global environment variables ##
variables:
  TENANT_DOMAIN: ping-aws.com
  DELETE_ENV_AFTER_PIPELINE: 'true'

## Compile stage ##
compile:
  stage: compile
  tags:
  - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
  - ./ci-scripts/compile/compile.sh
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/

## Build stage ##
deploy:
  stage: build
  tags:
  - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
  - ./ci-scripts/build/deploy.sh
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/

## Test stage ##
pd-tests:
  stage: test
  tags:
  - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
  - ./ci-scripts/test/run-test.sh pingdirectory
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/

pf-tests:
  stage: test
  tags:
  - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
  - ./ci-scripts/test/run-test.sh pingfederate
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/

pa-tests:
  stage: test
  tags:
    - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
    - ./ci-scripts/test/run-test.sh pingaccess
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/

integration-tests:
  stage: test
  tags:
    - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
    - ./ci-scripts/test/run-test.sh integration
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/

## Chaos testing stage ##
chaos-tests:
  stage: chaos
  tags:
  - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
  - ./ci-scripts/test/run-test.sh chaos
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/

## Cleanup stage ##
cleanup:
  stage: cleanup
  tags:
  - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
  - ./ci-scripts/cleanup/teardown.sh
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/